//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPEONES
    {
        public CAMPEONES()
        {
            this.CAMPEONES_MAS_JUGADOS_X_USUARIO = new HashSet<CAMPEONES_MAS_JUGADOS_X_USUARIO>();
        }
    
        public int idCampeones { get; set; }
        public string nombre { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual ICollection<CAMPEONES_MAS_JUGADOS_X_USUARIO> CAMPEONES_MAS_JUGADOS_X_USUARIO { get; set; }
    }
}
