//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA
    {
        public DIA()
        {
            this.DISPONIBILIDAD_X_JUGADOR = new HashSet<DISPONIBILIDAD_X_JUGADOR>();
        }
    
        public int idDia { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<DISPONIBILIDAD_X_JUGADOR> DISPONIBILIDAD_X_JUGADOR { get; set; }
    }
}
