//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISION
    {
        public DIVISION()
        {
            this.JUGADOR = new HashSet<JUGADOR>();
        }
    
        public int idDivision { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
    }
}
