//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.ADMIN_X_EQUIPO = new HashSet<ADMIN_X_EQUIPO>();
            this.JUGADORES_X_EQUIPO = new HashSet<JUGADORES_X_EQUIPO>();
            this.POSTULACION_EQUIPO_X_JUGADOR = new HashSet<POSTULACION_EQUIPO_X_JUGADOR>();
        }
    
        public int idEquipo { get; set; }
        [StringLength(25), Required , Display(Name = "Nombre de equipo")]
        public string nombreEquipo { get; set; }
        public string etiqueta { get; set; }
        public byte[] logo { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public string paginaWeb { get; set; }
    
        public virtual ICollection<ADMIN_X_EQUIPO> ADMIN_X_EQUIPO { get; set; }
        public virtual ICollection<JUGADORES_X_EQUIPO> JUGADORES_X_EQUIPO { get; set; }
        public virtual ICollection<POSTULACION_EQUIPO_X_JUGADOR> POSTULACION_EQUIPO_X_JUGADOR { get; set; }
    }
}
