//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADOR
    {
        public JUGADOR()
        {
            this.CAMPEONES_MAS_JUGADOS_X_USUARIO = new HashSet<CAMPEONES_MAS_JUGADOS_X_USUARIO>();
            this.DISPONIBILIDAD_X_JUGADOR = new HashSet<DISPONIBILIDAD_X_JUGADOR>();
            this.JUGADORES_X_EQUIPO = new HashSet<JUGADORES_X_EQUIPO>();
            this.POSTULACION_EQUIPO_X_JUGADOR = new HashSet<POSTULACION_EQUIPO_X_JUGADOR>();
            this.ROLES_JUGADOR_X_JUGADOR = new HashSet<ROLES_JUGADOR_X_JUGADOR>();
            this.TELEFONO_X_JUGADOR = new HashSet<TELEFONO_X_JUGADOR>();
        }
    
        public int idJugador { get; set; }
        public int IdDomicilio { get; set; }
        public int idDivision { get; set; }
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public byte[] foto { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string email { get; set; }
        public int telefono { get; set; }
        public string nombreInvocador { get; set; }
    
        public virtual ICollection<CAMPEONES_MAS_JUGADOS_X_USUARIO> CAMPEONES_MAS_JUGADOS_X_USUARIO { get; set; }
        public virtual ICollection<DISPONIBILIDAD_X_JUGADOR> DISPONIBILIDAD_X_JUGADOR { get; set; }
        public virtual DIVISION DIVISION { get; set; }
        public virtual DOMICILIO DOMICILIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<JUGADORES_X_EQUIPO> JUGADORES_X_EQUIPO { get; set; }
        public virtual ICollection<POSTULACION_EQUIPO_X_JUGADOR> POSTULACION_EQUIPO_X_JUGADOR { get; set; }
        public virtual ICollection<ROLES_JUGADOR_X_JUGADOR> ROLES_JUGADOR_X_JUGADOR { get; set; }
        public virtual ICollection<TELEFONO_X_JUGADOR> TELEFONO_X_JUGADOR { get; set; }
    }
}
