//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_USUARIOS
    {
        public ROLES_USUARIOS()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int idRol { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
