//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_JUGADOR
    {
        public ROLES_JUGADOR()
        {
            this.ROLES_JUGADOR_X_JUGADOR = new HashSet<ROLES_JUGADOR_X_JUGADOR>();
        }
    
        public int idRolJugador { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ROLES_JUGADOR_X_JUGADOR> ROLES_JUGADOR_X_JUGADOR { get; set; }
    }
}
