//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolArgentina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO_X_JUGADOR
    {
        public int idTelefonoXJugador { get; set; }
        public Nullable<int> idTipoTelefono { get; set; }
        public Nullable<int> idJugador { get; set; }
        public string telefono { get; set; }
    
        public virtual JUGADOR JUGADOR { get; set; }
        public virtual TIPO_TELEFONO TIPO_TELEFONO { get; set; }
    }
}
